# Place all the behaviors and hooks related to the matching controller here.
# All this logic will automatically be available in application.js.
# You can use CoffeeScript in this file: http://coffeescript.org/
jQuery ->
  setInterval("location.reload()", 30000);
  # ViewPortを取得
  vw = window.innerWidth;
  vh = window.innerHeight;

  w = [
    $('.word0'),
    $('.word1'),
    $('.word2'),
    $('.word3'),
    $('.word4'),
    $('.word5'),
    $('.word6'),
    $('.word7'),
    $('.word8'),
    $('.word9'),
  ];

  w_pos = [
    {
      'x': vw * 1 / 10
      'y': vh * 1 / 1000
    }
    {
      'x': vw * 2 / 10
      'y': vh * 2 / 1000
    }
    {
      'x': vw * 3 / 10
      'y': vh * 13 / 1000
    }
    {
      'x': vw * 4 / 10
      'y': vh * 2 / 1000
    }
    {
      'x': vw * 5 / 10
      'y': vh * 19 / 1000
    }
    {
      'x': vw * 6 / 10
      'y': vh * 4 / 1000
    }
    {
      'x': vw * 7 / 10
      'y': vh * 1 / 1000
    }
    {
      'x': vw * 8 / 10
      'y': vh * 6 / 1000
    }
    {
      'x': vw * 9 / 10
      'y': vh * 1 / 1000
    }
    {
      'x': vw * 10 / 10
      'y': vh * 1 / 1000
    }
  ]
  color = [
    'lime',
    'aqua',
    'yellow',
    'red',
    'fuchsia',
    'silver',
    'white',
    'lime',
    'aqua',
    'yellow'
  ]

  # ループ処理
  loop_do = ->
    # requestAnimFrame loop_do
    setTimeout loop_do, 1000 / 45
    step = 0
    while step < 10
      random = Math.random() * 11;
      n = step
      # ループ毎にxを加算
      w_pos[n].x += random
      w_pos[n].y += random
      # 文字を動かす
      w[n].css
        'top': String(w_pos[n].y) + 'px'
        'left': String(w_pos[n].x) + 'px'
        'color': color[n]
      
      if w_pos[n].x > vw or w_pos[n].x < 0
        w_pos[n].x = 0
      if w_pos[n].y > vh or w_pos[n].y < 0
        w_pos[n].y = 0
      
      step++
    

  window.requestAnimFrame = do ->
    window.requestAnimationFrame or window.webkitRequestAnimationFrame or window.mozRequestAnimationFrame or window.oRequestAnimationFrame or window.msRequestAnimationFrame or (callback) ->
      window.setTimeout callback, 1000 / 60
      return

  loop_do()

# ---
# generated by js2coffee 2.2.0